# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tinyPIDmonitor.ui'
#
# Created: Fri Mar 18 13:49:40 2011
#      by: PySide uic UI code generator
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from PyQt4.Qwt5 import *
class Ui_tinyPIDmonitor(object):
    def setupUi(self, tinyPIDmonitor):
        tinyPIDmonitor.setObjectName("tinyPIDmonitor")
        tinyPIDmonitor.resize(820, 501)
        self.centralwidget = QtGui.QWidget(tinyPIDmonitor)
        self.centralwidget.setObjectName("centralwidget")
        self.qwtPlot = QwtPlot(self.centralwidget)
        self.qwtPlot.setGeometry(QtCore.QRect(10, 10, 571, 451))
        self.qwtPlot.setObjectName("qwtPlot")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(600, 10, 211, 461))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.East)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.widget = QtGui.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(10, 10, 161, 91))
        self.widget.setObjectName("widget")
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.setpointSpinBox = QtGui.QSpinBox(self.widget)
        self.setpointSpinBox.setAccelerated(True)
        self.setpointSpinBox.setMaximum(255)
        self.setpointSpinBox.setObjectName("setpointSpinBox")
        self.gridLayout.addWidget(self.setpointSpinBox, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.outputSpinBox = QtGui.QSpinBox(self.widget)
        self.outputSpinBox.setAccelerated(True)
        self.outputSpinBox.setMaximum(255)
        self.outputSpinBox.setObjectName("outputSpinBox")
        self.gridLayout.addWidget(self.outputSpinBox, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.widget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.pvLabel = QtGui.QLabel(self.widget)
        self.pvLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pvLabel.setObjectName("pvLabel")
        self.gridLayout.addWidget(self.pvLabel, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.errorLabel = QtGui.QLabel(self.widget)
        self.errorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.errorLabel.setObjectName("errorLabel")
        self.gridLayout.addWidget(self.errorLabel, 3, 1, 1, 1)
        self.autoRadioButton = QtGui.QRadioButton(self.widget)
        self.autoRadioButton.setObjectName("autoRadioButton")
        self.gridLayout.addWidget(self.autoRadioButton, 0, 2, 1, 1)
        self.manRadioButton = QtGui.QRadioButton(self.widget)
        self.manRadioButton.setObjectName("manRadioButton")
        self.gridLayout.addWidget(self.manRadioButton, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.widget1 = QtGui.QWidget(self.tab_2)
        self.widget1.setGeometry(QtCore.QRect(20, 10, 141, 151))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridCheckBox = QtGui.QCheckBox(self.widget1)
        self.gridCheckBox.setObjectName("gridCheckBox")
        self.verticalLayout.addWidget(self.gridCheckBox)
        self.autoscaleCheckBox = QtGui.QCheckBox(self.widget1)
        self.autoscaleCheckBox.setObjectName("autoscaleCheckBox")
        self.verticalLayout.addWidget(self.autoscaleCheckBox)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtGui.QLabel(self.widget1)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.yminSpinBox = QtGui.QSpinBox(self.widget1)
        self.yminSpinBox.setAccelerated(True)
        self.yminSpinBox.setMaximum(255)
        self.yminSpinBox.setObjectName("yminSpinBox")
        self.gridLayout_2.addWidget(self.yminSpinBox, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.widget1)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.ymaxSpinBox = QtGui.QSpinBox(self.widget1)
        self.ymaxSpinBox.setAccelerated(True)
        self.ymaxSpinBox.setMinimum(50)
        self.ymaxSpinBox.setMaximum(255)
        self.ymaxSpinBox.setProperty("value", QtCore.QVariant(255))
        self.ymaxSpinBox.setObjectName("ymaxSpinBox")
        self.gridLayout_2.addWidget(self.ymaxSpinBox, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget1)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget1)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.viewsizeSpinBox = QtGui.QSpinBox(self.widget1)
        self.viewsizeSpinBox.setMinimum(1)
        self.viewsizeSpinBox.setMaximum(9999)
        self.viewsizeSpinBox.setObjectName("viewsizeSpinBox")
        self.gridLayout_2.addWidget(self.viewsizeSpinBox, 2, 1, 1, 1)
        self.scrollSpinBox = QtGui.QSpinBox(self.widget1)
        self.scrollSpinBox.setAccelerated(True)
        self.scrollSpinBox.setMaximum(100)
        self.scrollSpinBox.setObjectName("scrollSpinBox")
        self.gridLayout_2.addWidget(self.scrollSpinBox, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.widget2 = QtGui.QWidget(self.tab_3)
        self.widget2.setGeometry(QtCore.QRect(20, 10, 141, 148))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.portLabel = QtGui.QLabel(self.widget2)
        self.portLabel.setObjectName("portLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.portLabel)
        self.portLineEdit = QtGui.QLineEdit(self.widget2)
        self.portLineEdit.setObjectName("portLineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.portLineEdit)
        self.speedLabel = QtGui.QLabel(self.widget2)
        self.speedLabel.setObjectName("speedLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.speedLabel)
        self.speedLineEdit = QtGui.QLineEdit(self.widget2)
        self.speedLineEdit.setObjectName("speedLineEdit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.speedLineEdit)
        self.intervalLabel = QtGui.QLabel(self.widget2)
        self.intervalLabel.setObjectName("intervalLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.intervalLabel)
        self.intervalSpinBox = QtGui.QSpinBox(self.widget2)
        self.intervalSpinBox.setMinimum(1)
        self.intervalSpinBox.setMaximum(9999)
        self.intervalSpinBox.setProperty("value", QtCore.QVariant(1000))
        self.intervalSpinBox.setObjectName("intervalSpinBox")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.intervalSpinBox)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.connectCheckBox = QtGui.QCheckBox(self.widget2)
        self.connectCheckBox.setObjectName("connectCheckBox")
        self.verticalLayout_2.addWidget(self.connectCheckBox)
        self.connectButton = QtGui.QPushButton(self.widget2)
        self.connectButton.setObjectName("connectButton")
        self.verticalLayout_2.addWidget(self.connectButton)
        self.connectLabel = QtGui.QLabel(self.widget2)
        self.connectLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.connectLabel.setObjectName("connectLabel")
        self.verticalLayout_2.addWidget(self.connectLabel)
        self.tabWidget.addTab(self.tab_3, "")
        tinyPIDmonitor.setCentralWidget(self.centralwidget)

        self.retranslateUi(tinyPIDmonitor)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.gridCheckBox, QtCore.SIGNAL("toggled(bool)"), tinyPIDmonitor.gridEnable)
        QtCore.QObject.connect(self.autoscaleCheckBox, QtCore.SIGNAL("toggled(bool)"), tinyPIDmonitor.setAutoscale)
        QtCore.QObject.connect(self.yminSpinBox, QtCore.SIGNAL("valueChanged(int)"), tinyPIDmonitor.setYmin)
        QtCore.QObject.connect(self.ymaxSpinBox, QtCore.SIGNAL("valueChanged(int)"), tinyPIDmonitor.setYmax)
        QtCore.QObject.connect(self.viewsizeSpinBox, QtCore.SIGNAL("valueChanged(int)"), tinyPIDmonitor.setView)
        QtCore.QObject.connect(self.scrollSpinBox, QtCore.SIGNAL("valueChanged(int)"), tinyPIDmonitor.setScroll)
        QtCore.QObject.connect(self.autoRadioButton, QtCore.SIGNAL("toggled(bool)"), self.outputSpinBox.setDisabled)
        QtCore.QObject.connect(self.manRadioButton, QtCore.SIGNAL("toggled(bool)"), self.outputSpinBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(tinyPIDmonitor)

    def retranslateUi(self, tinyPIDmonitor):
        tinyPIDmonitor.setWindowTitle(QtGui.QApplication.translate("tinyPIDmonitor", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("tinyPIDmonitor", "SP:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("tinyPIDmonitor", "Output:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("tinyPIDmonitor", "PV:", None, QtGui.QApplication.UnicodeUTF8))
        self.pvLabel.setText(QtGui.QApplication.translate("tinyPIDmonitor", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("tinyPIDmonitor", "Error:", None, QtGui.QApplication.UnicodeUTF8))
        self.errorLabel.setText(QtGui.QApplication.translate("tinyPIDmonitor", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.autoRadioButton.setText(QtGui.QApplication.translate("tinyPIDmonitor", "auto", None, QtGui.QApplication.UnicodeUTF8))
        self.manRadioButton.setText(QtGui.QApplication.translate("tinyPIDmonitor", "man", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("tinyPIDmonitor", "Control", None, QtGui.QApplication.UnicodeUTF8))
        self.gridCheckBox.setText(QtGui.QApplication.translate("tinyPIDmonitor", "Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.autoscaleCheckBox.setText(QtGui.QApplication.translate("tinyPIDmonitor", "Autoscale", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("tinyPIDmonitor", "ymin", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("tinyPIDmonitor", "ymax", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("tinyPIDmonitor", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("tinyPIDmonitor", "Scroll", None, QtGui.QApplication.UnicodeUTF8))
        self.viewsizeSpinBox.setSuffix(QtGui.QApplication.translate("tinyPIDmonitor", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.scrollSpinBox.setSuffix(QtGui.QApplication.translate("tinyPIDmonitor", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("tinyPIDmonitor", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.portLabel.setText(QtGui.QApplication.translate("tinyPIDmonitor", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.portLineEdit.setText(QtGui.QApplication.translate("tinyPIDmonitor", "/dev/ttyUSB0", None, QtGui.QApplication.UnicodeUTF8))
        self.speedLabel.setText(QtGui.QApplication.translate("tinyPIDmonitor", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.speedLineEdit.setText(QtGui.QApplication.translate("tinyPIDmonitor", "9600", None, QtGui.QApplication.UnicodeUTF8))
        self.intervalLabel.setText(QtGui.QApplication.translate("tinyPIDmonitor", "Interval", None, QtGui.QApplication.UnicodeUTF8))
        self.intervalSpinBox.setSuffix(QtGui.QApplication.translate("tinyPIDmonitor", "ms", None, QtGui.QApplication.UnicodeUTF8))
        self.connectCheckBox.setText(QtGui.QApplication.translate("tinyPIDmonitor", "Autoconnect", None, QtGui.QApplication.UnicodeUTF8))
        self.connectButton.setText(QtGui.QApplication.translate("tinyPIDmonitor", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("tinyPIDmonitor", "Com", None, QtGui.QApplication.UnicodeUTF8))

#from qwt_plot import QwtPlot
