# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Fri Mar  4 17:33:11 2011
#      by: PySide uic UI code generator
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(658, 538)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 641, 491))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget = QtGui.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 621, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stopRadioButton = QtGui.QRadioButton(self.gridLayoutWidget)
        self.stopRadioButton.setObjectName("stopRadioButton")
        self.gridLayout.addWidget(self.stopRadioButton, 0, 0, 1, 1)
        self.manualRadioButton = QtGui.QRadioButton(self.gridLayoutWidget)
        self.manualRadioButton.setObjectName("manualRadioButton")
        self.gridLayout.addWidget(self.manualRadioButton, 1, 0, 1, 1)
        self.autoRadioButton = QtGui.QRadioButton(self.gridLayoutWidget)
        self.autoRadioButton.setObjectName("autoRadioButton")
        self.gridLayout.addWidget(self.autoRadioButton, 2, 0, 1, 1)
        self.outputvalueHorizontalSlider = QtGui.QSlider(self.gridLayoutWidget)
        self.outputvalueHorizontalSlider.setMaximum(255)
        self.outputvalueHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.outputvalueHorizontalSlider.setObjectName("outputvalueHorizontalSlider")
        self.gridLayout.addWidget(self.outputvalueHorizontalSlider, 1, 2, 1, 1)
        self.setvalueHorizontalSlider = QtGui.QSlider(self.gridLayoutWidget)
        self.setvalueHorizontalSlider.setMaximum(255)
        self.setvalueHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.setvalueHorizontalSlider.setObjectName("setvalueHorizontalSlider")
        self.gridLayout.addWidget(self.setvalueHorizontalSlider, 0, 2, 1, 1)
        self.setvalueSpinBox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.setvalueSpinBox.setMaximum(255)
        self.setvalueSpinBox.setObjectName("setvalueSpinBox")
        self.gridLayout.addWidget(self.setvalueSpinBox, 0, 3, 1, 1)
        self.outputvalueSpinBox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.outputvalueSpinBox.setMaximum(255)
        self.outputvalueSpinBox.setObjectName("outputvalueSpinBox")
        self.gridLayout.addWidget(self.outputvalueSpinBox, 1, 3, 1, 1)
        self.processvalueSpinBox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.processvalueSpinBox.setEnabled(False)
        self.processvalueSpinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.processvalueSpinBox.setMaximum(255)
        self.processvalueSpinBox.setObjectName("processvalueSpinBox")
        self.gridLayout.addWidget(self.processvalueSpinBox, 2, 3, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 4, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 4, 1, 1)
        self.processvalueProgressBar = QtGui.QProgressBar(self.gridLayoutWidget)
        self.processvalueProgressBar.setMaximum(255)
        self.processvalueProgressBar.setProperty("value", QtCore.QVariant(0))
        self.processvalueProgressBar.setObjectName("processvalueProgressBar")
        self.gridLayout.addWidget(self.processvalueProgressBar, 2, 2, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.layoutWidget = QtGui.QWidget(self.tab_3)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 631, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget1 = QtGui.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 192, 111))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.kpLabel = QtGui.QLabel(self.layoutWidget1)
        self.kpLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.kpLabel.setObjectName("kpLabel")
        self.gridLayout_2.addWidget(self.kpLabel, 0, 0, 1, 1)
        self.kpDoubleSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget1)
        self.kpDoubleSpinBox.setDecimals(1)
        self.kpDoubleSpinBox.setObjectName("kpDoubleSpinBox")
        self.gridLayout_2.addWidget(self.kpDoubleSpinBox, 0, 1, 1, 1)
        self.kiLabel = QtGui.QLabel(self.layoutWidget1)
        self.kiLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.kiLabel.setObjectName("kiLabel")
        self.gridLayout_2.addWidget(self.kiLabel, 1, 0, 1, 1)
        self.kiSpinBox = QtGui.QSpinBox(self.layoutWidget1)
        self.kiSpinBox.setObjectName("kiSpinBox")
        self.gridLayout_2.addWidget(self.kiSpinBox, 1, 1, 1, 1)
        self.kdLabel = QtGui.QLabel(self.layoutWidget1)
        self.kdLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.kdLabel.setObjectName("kdLabel")
        self.gridLayout_2.addWidget(self.kdLabel, 2, 0, 1, 1)
        self.kdSpinBox = QtGui.QSpinBox(self.layoutWidget1)
        self.kdSpinBox.setObjectName("kdSpinBox")
        self.gridLayout_2.addWidget(self.kdSpinBox, 2, 1, 1, 1)
        self.tvLabel = QtGui.QLabel(self.layoutWidget1)
        self.tvLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tvLabel.setObjectName("tvLabel")
        self.gridLayout_2.addWidget(self.tvLabel, 2, 2, 1, 1)
        self.tvDoubleSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget1)
        self.tvDoubleSpinBox.setDecimals(1)
        self.tvDoubleSpinBox.setObjectName("tvDoubleSpinBox")
        self.gridLayout_2.addWidget(self.tvDoubleSpinBox, 2, 3, 1, 1)
        self.tnLabel = QtGui.QLabel(self.layoutWidget1)
        self.tnLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tnLabel.setObjectName("tnLabel")
        self.gridLayout_2.addWidget(self.tnLabel, 1, 2, 1, 1)
        self.tnDoubleSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget1)
        self.tnDoubleSpinBox.setDecimals(1)
        self.tnDoubleSpinBox.setObjectName("tnDoubleSpinBox")
        self.gridLayout_2.addWidget(self.tnDoubleSpinBox, 1, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.parametersButtonBox = QtGui.QDialogButtonBox(self.layoutWidget1)
        self.parametersButtonBox.setStandardButtons(QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.Reset)
        self.parametersButtonBox.setObjectName("parametersButtonBox")
        self.verticalLayout_2.addWidget(self.parametersButtonBox)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget2 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 20, 192, 109))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.modeLabel = QtGui.QLabel(self.layoutWidget2)
        self.modeLabel.setObjectName("modeLabel")
        self.gridLayout_3.addWidget(self.modeLabel, 0, 0, 1, 1)
        self.modeComboBox = QtGui.QComboBox(self.layoutWidget2)
        self.modeComboBox.setObjectName("modeComboBox")
        self.modeComboBox.addItem(QtCore.QString())
        self.modeComboBox.addItem(QtCore.QString())
        self.gridLayout_3.addWidget(self.modeComboBox, 0, 1, 1, 1)
        self.valueLabel = QtGui.QLabel(self.layoutWidget2)
        self.valueLabel.setObjectName("valueLabel")
        self.gridLayout_3.addWidget(self.valueLabel, 1, 0, 1, 1)
        self.valueSpinBox = QtGui.QSpinBox(self.layoutWidget2)
        self.valueSpinBox.setAccelerated(True)
        self.valueSpinBox.setMaximum(255)
        self.valueSpinBox.setObjectName("valueSpinBox")
        self.gridLayout_3.addWidget(self.valueSpinBox, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        spacerItem = QtGui.QSpacerItem(20, 23, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.initialvaluesButtonBox = QtGui.QDialogButtonBox(self.layoutWidget2)
        self.initialvaluesButtonBox.setStandardButtons(QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.Reset)
        self.initialvaluesButtonBox.setObjectName("initialvaluesButtonBox")
        self.verticalLayout_3.addWidget(self.initialvaluesButtonBox)
        self.horizontalLayout.addWidget(self.groupBox_2)
        spacerItem1 = QtGui.QSpacerItem(190, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.graphicsView = QtGui.QGraphicsView(self.verticalLayoutWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 658, 20))
        self.menubar.setObjectName("menubar")
        self.menuTinyPIDqt = QtGui.QMenu(self.menubar)
        self.menuTinyPIDqt.setObjectName("menuTinyPIDqt")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuTinyPIDqt.addAction(self.actionQuit)
        self.menubar.addAction(self.menuTinyPIDqt.menuAction())
        self.kpLabel.setBuddy(self.kpDoubleSpinBox)
        self.kiLabel.setBuddy(self.kiSpinBox)
        self.kdLabel.setBuddy(self.kdSpinBox)
        self.tvLabel.setBuddy(self.tvDoubleSpinBox)
        self.tnLabel.setBuddy(self.tnDoubleSpinBox)
        self.modeLabel.setBuddy(self.modeComboBox)
        self.valueLabel.setBuddy(self.valueSpinBox)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QObject.connect(self.outputvalueHorizontalSlider, QtCore.SIGNAL("valueChanged(int)"), self.outputvalueSpinBox.setValue)
        QtCore.QObject.connect(self.outputvalueSpinBox, QtCore.SIGNAL("valueChanged(int)"), self.outputvalueHorizontalSlider.setValue)
        QtCore.QObject.connect(self.setvalueHorizontalSlider, QtCore.SIGNAL("valueChanged(int)"), self.setvalueSpinBox.setValue)
        QtCore.QObject.connect(self.setvalueSpinBox, QtCore.SIGNAL("valueChanged(int)"), self.setvalueHorizontalSlider.setValue)
        QtCore.QObject.connect(self.manualRadioButton, QtCore.SIGNAL("toggled(bool)"), self.outputvalueHorizontalSlider.setEnabled)
        QtCore.QObject.connect(self.autoRadioButton, QtCore.SIGNAL("toggled(bool)"), self.outputvalueHorizontalSlider.setDisabled)
        QtCore.QObject.connect(self.manualRadioButton, QtCore.SIGNAL("toggled(bool)"), self.outputvalueSpinBox.setEnabled)
        QtCore.QObject.connect(self.autoRadioButton, QtCore.SIGNAL("toggled(bool)"), self.outputvalueSpinBox.setDisabled)
        QtCore.QObject.connect(self.stopRadioButton, QtCore.SIGNAL("toggled(bool)"), self.outputvalueHorizontalSlider.setEnabled)
        QtCore.QObject.connect(self.stopRadioButton, QtCore.SIGNAL("toggled(bool)"), self.outputvalueSpinBox.setEnabled)
        QtCore.QObject.connect(self.processvalueSpinBox, QtCore.SIGNAL("valueChanged(int)"), self.processvalueProgressBar.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "tinyPIDqt", None, QtGui.QApplication.UnicodeUTF8))
        self.stopRadioButton.setText(QtGui.QApplication.translate("MainWindow", "stop", None, QtGui.QApplication.UnicodeUTF8))
        self.manualRadioButton.setText(QtGui.QApplication.translate("MainWindow", "manual", None, QtGui.QApplication.UnicodeUTF8))
        self.autoRadioButton.setText(QtGui.QApplication.translate("MainWindow", "automatic", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Setpoint", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Output Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Process Value", None, QtGui.QApplication.UnicodeUTF8))
        self.processvalueProgressBar.setFormat(QtGui.QApplication.translate("MainWindow", "%p", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Overview", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.kpLabel.setText(QtGui.QApplication.translate("MainWindow", "Kp", None, QtGui.QApplication.UnicodeUTF8))
        self.kiLabel.setText(QtGui.QApplication.translate("MainWindow", "Ki", None, QtGui.QApplication.UnicodeUTF8))
        self.kdLabel.setText(QtGui.QApplication.translate("MainWindow", "Kd", None, QtGui.QApplication.UnicodeUTF8))
        self.tvLabel.setText(QtGui.QApplication.translate("MainWindow", "Tv", None, QtGui.QApplication.UnicodeUTF8))
        self.tnLabel.setText(QtGui.QApplication.translate("MainWindow", "Tn", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Initial Values", None, QtGui.QApplication.UnicodeUTF8))
        self.modeLabel.setText(QtGui.QApplication.translate("MainWindow", "Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.modeComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "automatic", None, QtGui.QApplication.UnicodeUTF8))
        self.modeComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "manual", None, QtGui.QApplication.UnicodeUTF8))
        self.valueLabel.setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTinyPIDqt.setTitle(QtGui.QApplication.translate("MainWindow", "tinyPIDqt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "quit", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

